"""gift and gift statuses

Revision ID: 434085e02996
Revises: 8253d380990f
Create Date: 2025-09-09 11:42:26.170667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '434085e02996'
down_revision: Union[str, Sequence[str], None] = '8253d380990f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_statuses',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('gifts',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('buyer_uid', sa.Uuid(), nullable=True),
    sa.Column('recipient_uid', sa.Uuid(), nullable=True),
    sa.Column('status_uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_uid'], ['persons.uid'], ),
    sa.ForeignKeyConstraint(['recipient_uid'], ['persons.uid'], ),
    sa.ForeignKeyConstraint(['status_uid'], ['gift_statuses.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gifts')
    op.drop_table('gift_statuses')
    # ### end Alembic commands ###
